// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package dbgen

import (
	"context"
	"time"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO
  transactions (user_id, amount, category, description, date, created_at)
VALUES
  (?, ?, ?, ?, ?, ?)
RETURNING
  id, user_id, amount, category, description, date, created_at
`

type CreateTransactionParams struct {
	UserID      string    `json:"user_id"`
	Amount      float64   `json:"amount"`
	Category    string    `json:"category"`
	Description *string   `json:"description"`
	Date        string    `json:"date"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Category,
		arg.Description,
		arg.Date,
		arg.CreatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Category,
		&i.Description,
		&i.Date,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM
  transactions
WHERE
  id = ? AND user_id = ?
`

type DeleteTransactionParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTransaction, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const summaryForMonth = `-- name: SummaryForMonth :many
SELECT
  category,
  SUM(amount) AS total
FROM
  transactions
WHERE
  user_id = ?
  AND substr(date, 1, 7) = ?
GROUP BY
  category
`

type SummaryForMonthParams struct {
	UserID string `json:"user_id"`
	Date   string `json:"date"`
}

type SummaryForMonthRow struct {
	Category string   `json:"category"`
	Total    *float64 `json:"total"`
}

func (q *Queries) SummaryForMonth(ctx context.Context, arg SummaryForMonthParams) ([]SummaryForMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, summaryForMonth, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummaryForMonthRow{}
	for rows.Next() {
		var i SummaryForMonthRow
		if err := rows.Scan(&i.Category, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transactionsForMonth = `-- name: TransactionsForMonth :many
SELECT
  id, user_id, amount, category, description, date, created_at
FROM
  transactions
WHERE
  user_id = ?
  AND substr(date, 1, 7) = ?
ORDER BY
  date DESC, id DESC
`

type TransactionsForMonthParams struct {
	UserID string `json:"user_id"`
	Date   string `json:"date"`
}

func (q *Queries) TransactionsForMonth(ctx context.Context, arg TransactionsForMonthParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, transactionsForMonth, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Category,
			&i.Description,
			&i.Date,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
