// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package dbgen

import (
	"context"
	"time"
)

const categoryTotalsForDay = `-- name: CategoryTotalsForDay :many
SELECT
  category,
  SUM(amount) AS total
FROM
  transactions
WHERE
  user_id = ?
  AND date = ?
GROUP BY
  category
`

type CategoryTotalsForDayParams struct {
	UserID string `json:"user_id"`
	Date   string `json:"date"`
}

type CategoryTotalsForDayRow struct {
	Category string   `json:"category"`
	Total    *float64 `json:"total"`
}

func (q *Queries) CategoryTotalsForDay(ctx context.Context, arg CategoryTotalsForDayParams) ([]CategoryTotalsForDayRow, error) {
	rows, err := q.db.QueryContext(ctx, categoryTotalsForDay, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryTotalsForDayRow{}
	for rows.Next() {
		var i CategoryTotalsForDayRow
		if err := rows.Scan(&i.Category, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const categoryTotalsForMonth = `-- name: CategoryTotalsForMonth :many
SELECT
  category,
  SUM(amount) AS total
FROM
  transactions
WHERE
  user_id = ?
  AND substr(date, 1, 7) = ?
GROUP BY
  category
`

type CategoryTotalsForMonthParams struct {
	UserID string `json:"user_id"`
	Date   string `json:"date"`
}

type CategoryTotalsForMonthRow struct {
	Category string   `json:"category"`
	Total    *float64 `json:"total"`
}

func (q *Queries) CategoryTotalsForMonth(ctx context.Context, arg CategoryTotalsForMonthParams) ([]CategoryTotalsForMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, categoryTotalsForMonth, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryTotalsForMonthRow{}
	for rows.Next() {
		var i CategoryTotalsForMonthRow
		if err := rows.Scan(&i.Category, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO
  transactions (user_id, amount, category, description, date, created_at)
VALUES
  (?, ?, ?, ?, ?, ?)
RETURNING
  id, user_id, amount, category, description, date, created_at
`

type CreateTransactionParams struct {
	UserID      string    `json:"user_id"`
	Amount      float64   `json:"amount"`
	Category    string    `json:"category"`
	Description *string   `json:"description"`
	Date        string    `json:"date"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Category,
		arg.Description,
		arg.Date,
		arg.CreatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Category,
		&i.Description,
		&i.Date,
		&i.CreatedAt,
	)
	return i, err
}

const dayTotalsForMonth = `-- name: DayTotalsForMonth :many
SELECT
  date,
  SUM(amount) AS total
FROM
  transactions
WHERE
  user_id = ?
  AND substr(date, 1, 7) = ?
GROUP BY
  date
ORDER BY
  date
`

type DayTotalsForMonthParams struct {
	UserID string `json:"user_id"`
	Date   string `json:"date"`
}

type DayTotalsForMonthRow struct {
	Date  string   `json:"date"`
	Total *float64 `json:"total"`
}

func (q *Queries) DayTotalsForMonth(ctx context.Context, arg DayTotalsForMonthParams) ([]DayTotalsForMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, dayTotalsForMonth, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DayTotalsForMonthRow{}
	for rows.Next() {
		var i DayTotalsForMonthRow
		if err := rows.Scan(&i.Date, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM
  transactions
WHERE
  id = ? AND user_id = ?
`

type DeleteTransactionParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTransaction, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listBudgets = `-- name: ListBudgets :many
SELECT
  category, period, amount
FROM
  budgets
WHERE
  user_id = ?
`

type ListBudgetsRow struct {
	Category string  `json:"category"`
	Period   string  `json:"period"`
	Amount   float64 `json:"amount"`
}

func (q *Queries) ListBudgets(ctx context.Context, userID string) ([]ListBudgetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBudgets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetsRow{}
	for rows.Next() {
		var i ListBudgetsRow
		if err := rows.Scan(&i.Category, &i.Period, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transactionsForMonth = `-- name: TransactionsForMonth :many
SELECT
  id, user_id, amount, category, description, date, created_at
FROM
  transactions
WHERE
  user_id = ?
  AND substr(date, 1, 7) = ?
ORDER BY
  date DESC, id DESC
`

type TransactionsForMonthParams struct {
	UserID string `json:"user_id"`
	Date   string `json:"date"`
}

func (q *Queries) TransactionsForMonth(ctx context.Context, arg TransactionsForMonthParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, transactionsForMonth, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Category,
			&i.Description,
			&i.Date,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBudget = `-- name: UpsertBudget :exec
INSERT INTO
  budgets (user_id, category, period, amount)
VALUES
  (?, ?, ?, ?)
ON CONFLICT (user_id, category) DO UPDATE SET
  period = excluded.period,
  amount = excluded.amount
`

type UpsertBudgetParams struct {
	UserID   string  `json:"user_id"`
	Category string  `json:"category"`
	Period   string  `json:"period"`
	Amount   float64 `json:"amount"`
}

func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) error {
	_, err := q.db.ExecContext(ctx, upsertBudget,
		arg.UserID,
		arg.Category,
		arg.Period,
		arg.Amount,
	)
	return err
}
